networks:
  devopsproj_app-network:
    external: true

services:
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: aaa
      MYSQL_DATABASE: stationSki
    ports:
      - "3306:3306"
    networks:
      - devopsproj_app-network
    volumes:
      - mysql_data:/var/lib/mysql

  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - mysql
    ports:
      - "8082:8082"
    networks:
      - devopsproj_app-network

volumes:
  mysql_data:
